value_01 = int(input('enter the first Number:'))
value_02 = int(input('enter the second Number'))
print('Addition:',value_01+value_02)
print('Addition:',type(value_01+value_02))
print('*'*50)
value_01 = int(input('enter the first Number:'))
value_02 = int(input('enter the second Number:'))
print('Subtraction:',value_01-value_02)
print('subtraction:',type(value_01-value_02))
print('+'*50)
value_01 = int(input('enter the first number'))
value_02 = int(input('enter the second number'))
print('multiplication:',value_01*value_02)
print('multiplication:',type(value_01*value_02))
print('='*50)

value_01 = int(input('enter the first number'))
value_02 = int(input('enter the second number'))
print('float division',value_01/value_02)
print('float division:',type(value_01/value_02))
print('/'*50)